#
# .travis.yaml contains YAML-formatted (http://www.yaml.org/) build
# instructions for continuous integration via Travis CI
# (http://docs.travis-ci.com/).
#

# Only use continuous integration on the master branch
branches: 
    only: 
        - GUI

# Send notifications on every build failure to comitter and author. Never send
# notifications for sucessful builds.
notifications:
    email:
        on_success: never

# We're not really using C (but Red and Rebol, of course), but setting language
# to C disables Travis CI's Ruby-specific defaults.
language: c

# We run the Red and Red/System test suites separately, to don't run against
# Travis CI's current 50 minute execution time limitation.
env:
    - BUILD_RED=1

before_install:
    - sudo apt-get update

install:
    # 32b "multiarch" libraries are necessary to run 32b binaries on the 64b
    # Travis VM.
    - sudo apt-get install -y libc6:i386 libcurl3:i386
    # Rebol 2 is necessary for building Red.
    - wget http://static.red-lang.org/tmp/rebol
    - chmod +x rebol
    - sudo mv ./rebol /usr/local/bin/rebol2
    - wget https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2
    - tar xjf linux-amd64-github-release.tar.bz2
    - sudo mv ./bin/linux/amd64/github-release /usr/local/bin/github-release

before_script:
    - rebol2 -qws red.r -d -t Darwin environment/console/console.red

script:
    - github-release upload -s 06f75977809f89ad5baf9afa641a96ef20455fea --user qtxie --repo red --tag v0.6.3 --name "console" --file console